name = "pink-slips-rooms"
main = "worker.ts"
compatibility_date = "2026-09-01"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "MatchRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MatchRoom"]
